### ISSUE TITLE
No Error logged when encountering an error configuration ES

### ISSUE THREAD

**Issue by JD1337** [bitnami/bitnami-docker-elasticsearch#50] opened 2018-11-14 01:58 UTC
**Description**

When trying to install plugins, setup can fail and prematurely stop task without logging and error

**Steps to reproduce the issue:**

docker run --name test  -e ELASTICSEARCH_PLUGINS=discovery-ec2  -d bitnami/elasticsearch:6.4.3-debian-9-r0

**Describe the results you received:**

> Welcome to the Bitnami elasticsearch container
> Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
> Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
> Send us your feedback at containers@bitnami.com
> 
> INFO  ==> ** Starting Elasticsearch setup **
> INFO  ==> Configuring/Initializing Elasticsearch...
> INFO  ==> Configuration Elasticsearch cluster settings...

Then docker task stops without any further logs

next step on a successful run is normally
> INFO  ==> ** Elasticsearch setup finished! **

**Describe the results you expected:**

- Log an error on installing plugin
- Continue to load Elasticsearch
the ES .yml can have a requirement set "plugin.mandatory:" which should be used to prevent the ES node from running if a plugin is missing, rather than the script stopping.
**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built:        Tue Nov 14 22:03:51 2017
 OS/Arch:      linux/amd64

also happens on 18.06.1-ce no difference (AWS ECS)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Occuring in both AWS Amazon Linux 2 ECS Optomised Instance (ami-0231cd5b17565f0b1) and Amazon Linux 2 local VM

**Comment by juan131** [comment] 2018-11-14 09:30
Hi @JD1337 

You can increase the logs verbosity and check what's going using the env. variable **BITNAMI_DEBUG=true**. For instance:

```
)$  docker run --name test -e ELASTICSEARCH_PLUGINS=discovery-ec2 -e BITNAMI_DEBUG=true bitnami/elasticsearch:6.4.3-debian-9-r0

Welcome to the Bitnami elasticsearch container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting Elasticsearch setup **
DEBUG ==> Validating Kernel settings...
DEBUG ==> Validating settings in ELASTICSEARCH_* env vars...
INFO  ==> Configuring/Initializing Elasticsearch...
DEBUG ==> Ensuring expected directories/files exist...
DEBUG ==> Setting default configuration
INFO  ==> Configuration Elasticsearch cluster settings...
DEBUG ==> Configure Elasticsearch Node type...
DEBUG ==> Using specified values for Xmx and Xms heap options...
DEBUG ==> Setting '-Xmx1024m -Xms1024m' heap options...
DEBUG ==> Installing plugins: discovery-ec2
DEBUG ==> Installing plugin: discovery-ec2
Checking if url exists: https://artifacts.elastic.co/downloads/elasticsearch-plugins/discovery-ec2/discovery-ec2-linux-x86_64-6.4.3.zip
-> Downloading discovery-ec2 from elastic
Retrieving zip from https://artifacts.elastic.co/downloads/elasticsearch-plugins/discovery-ec2/discovery-ec2-6.4.3.zip
[=================================================] 100%??
- Plugin information:
Name: discovery-ec2
Description: The EC2 discovery plugin allows to use AWS API for the unicast discovery mechanism.
Version: 6.4.3
Elasticsearch Version: 6.4.3
Java Version: 1.8
Native Controller: false
Extended Plugins: []
 * Classname: org.elasticsearch.discovery.ec2.Ec2DiscoveryPlugin
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.net.SocketPermission * connect,resolve
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
Exception in thread "main" java.nio.file.FileSystemException: /opt/bitnami/elasticsearch/config/discovery-ec2: Operation not permitted
```

> ES .yml can have a requirement set "plugin.mandatory:" which should be used to prevent the ES node from running if a plugin is missing, rather than the script stopping.

I totally agree with that. As you mentioned we can specify some plugins to be mandatory as described in the link below:

https://www.elastic.co/guide/en/elasticsearch/plugins/current/_plugins_directory.html

Please check the PR below to implement that:

https://github.com/bitnami/bitnami-docker-elasticsearch/pull/51

**Comment by keyboardscience** [comment] 2018-11-17 00:30
@juan131 sorry for issue necromancy, but I think this is an issue of the uid 1001 user writing to `/opt/bitnami/elasticsearch/config/<plugin-name>/?.*$` from the `elasticsearch-plugin install <plugin-name>` and dying after the `FileSystemException` is thrown. 

e.g.
```
I have no name!@62343d68923d:/$ elasticsearch-plugin install repository-s3
-> Downloading repository-s3 from elastic
[=================================================] 100%??
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission es.allow_insecure_settings read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]y
Exception in thread "main" java.nio.file.FileSystemException: /opt/bitnami/elasticsearch/config/repository-s3: Operation not permitted
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
...
```

To be honest, I'm not familiar enough with ES configuration to know if plugin destination relative to the config directory is nominal. However, uid 1001 would need to have write permission to create anything (currently seems to be 775).

```
I have no name!@983c3de5d288:/$ stat /opt/bitnami/elasticsearch/config/
  File: /opt/bitnami/elasticsearch/config/
  Size: 104             Blocks: 0          IO Block: 4096   directory
Device: 9fh/159d        Inode: 6640        Links: 1
Access: (0775/drwxrwxr-x)  Uid: (    0/    root)   Gid: (    0/    root)
```

My use is from a slightly modified version of your helm chart on a 1.11 cluster with FSGroup in the PodSecurityContext set to 1001. Perhaps this is a misunderstanding on my part, but I think FSGroup only applies to mounted volumes.

Debug log:
```
INFO  ==> ** Starting Elasticsearch setup **
DEBUG ==> Validating Kernel settings...
DEBUG ==> Validating settings in ELASTICSEARCH_* env vars...
INFO  ==> Configuring/Initializing Elasticsearch...
DEBUG ==> Detected persisted data from previous deployments
DEBUG ==> Ensuring expected directories/files exist...
DEBUG ==> Setting default configuration
INFO  ==> Configuration Elasticsearch cluster settings...
DEBUG ==> Configure Elasticsearch Node type...
DEBUG ==> Using specified values for Xmx and Xms heap options...
DEBUG ==> Setting '-Xmx4G -Xms4G' heap options...
DEBUG ==> Custom configuration detected. Injecting...
DEBUG ==> Installing plugins: repository-s3
DEBUG ==> Installing plugin: repository-s3
Checking if url exists: https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-linux-x86_64-6.4.3.zip
-> Downloading repository-s3 from elastic
Retrieving zip from https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-6.4.3.zip
[=================================================] 100%??
- Plugin information:
Name: repository-s3
Description: The S3 repository plugin adds S3 repositories
Version: 6.4.3
Elasticsearch Version: 6.4.3
Java Version: 1.8
Native Controller: false
Extended Plugins: []
 * Classname: org.elasticsearch.repositories.s3.S3RepositoryPlugin
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission es.allow_insecure_settings read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
Exception in thread "main" java.nio.file.FileSystemException: /opt/bitnami/elasticsearch/config/repository-s3: Operation not permitted
```

**Comment by tompizmor** [comment] 2018-11-19 16:11
Hi @keyboardscience,

I could also reproduce the error so I will re-open the issue. We will update it once we have more information, but as you said, it seems a permissions error while trying to install a plugin.

**Comment by jbianquetti-nami** [comment] 2019-04-11 14:29
Related: https://github.com/elastic/elasticsearch/issues/40969

**Comment by juan131** [comment] 2019-11-21 08:15
Hi everyone,

We just released a new revision of ES including a fix that allow users to install plugins (such as `ingest-geoip`).

As a consequence, this image doesn't work with K8s distributions which use non-root users with arbitrary UIDs. 

More info at: https://github.com/bitnami/bitnami-docker-elasticsearch/blob/master/README.md#685-debian-9-r0-685-ol-7-r1-742-debian-9-r10-742-ol-7-r27

**Comment by marcosbc** [comment] 2020-05-07 13:00
Closing since this seems to be resolved.

**Comment by jjo** [comment] 2020-05-13 00:09
I tried to use `ELASTICSEARCH_PLUGINS=repository-s3` in a Kubernetes environment with UID=1001, but failed silently, reproducing in local docker:

* simple run
```
$ docker run -it -u 1001 -e ELASTICSEARCH_PLUGINS=repository-s3 bitnami/elasticsearch:6.8.8-debian-10-r48 
[...]
 00:05:06.76 INFO  ==> Setting default configuration
 00:05:06.78 INFO  ==> Configuring Elasticsearch cluster settings...
$ echo $?
1
```

* with debugging, reason is clear now:
```
$ docker run -it -u 1001 -e BITNAMI_DEBUG=true -e ELASTICSEARCH_PLUGINS=repository-s3 bitnami/elasticsearch:6.8.8-debian-10-r48 
Checking if url exists: https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-linux-x86_64-6.8.8.zip
-> Downloading repository-s3 from elastic
Retrieving zip from https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-6.8.8.zip
ERROR: plugin directory [/opt/bitnami/elasticsearch/plugins/repository-s3] already exists; if you need to update the plugin, uninstall it first
 using command 'remove repository-s3'
```

* verifying indeed `repository-s3` comes included by default ?
```
$ docker run -it --entrypoint=/bin/bash bitnami/elasticsearch:6.8.8-debian-10-r48 -c "ls -ald /opt/bitnami/elasticsearch/plugins/*"
drwxrwxr-x 1 1001 root 4096 May  8 09:46 /opt/bitnami/elasticsearch/plugins/repository-s3
```
IMO this particular plugin inclusion should be documented, or the container initialization protected to either rm -rf the particular plugin directory before install or warn about its existence and continue.

**Comment by juan131** [comment] 2020-05-13 06:58
Hi @jjo 

That's indeed the unique plugin included by default, but I agree with you @jjo this should be clearly stated in the container's **README.md**.

I created this PR to document it: https://github.com/bitnami/bitnami-docker-elasticsearch/pull/76

**Comment by marcosbc** [comment] 2020-05-13 17:59
@jjo You're actually correct. We recently introduced a fix for this issue, but when https://github.com/bitnami/bitnami-docker-elasticsearch/pull/75 was merged, it got removed (probably due to an outdated Git branch).

I'm working on re-adding the required logic and launching a new release.

**Comment by marcosbc** [comment] 2020-05-14 08:05
@jjo Check out the tags and `6.8.9-debian-10-r0` and `7.7.0-debian-10-r0`, which were released last night. They include a fix that should allow you to specify `ELASTICSEARC_PLUGINS=repository-s3` without issues, so they are also included in the `plugin.mandatory` section in Elasticsearch's `elasticsearch.yml` configuration file.

**Closed** 2021-12-27 23:29 UTC
Labels: on-hold
